name: Cupy Test

on:
  workflow_dispatch:

jobs:
  Pylops_Cupy_Testing:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print checked code and check environments
        run: |
          ls -lah
          echo $(pwd)
          echo $(which python3)
          echo $(which pip3)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install flake8 pytest
          pip install -r requirements-dev.txt
          pip install -r requirements-torch.txt
      - name: Run Install
        run: pip install --upgrade --force-reinstall .
      - name: Run Numpy Test 
        env:
          OMP_NUM_THREADS: 32
          CUPY_PYLOPS: 0
          TEST_CUPY_PYLOPS: 0
        run: |
          srun -t 00:30:00 -N 1 -n 1 -c 64 --cpu-bind=cores \
          -q interactive -C cpu \
          pytest pytests/test_basicoperators.py
      - name: Run Cupy Test 
        env:
          OMP_NUM_THREADS: 32
          CUPY_PYLOPS: 1
          TEST_CUPY_PYLOPS: 1
        run: |
          srun -t 00:30:00 -N 1 -n 1 -c 64 --cpu-bind=cores \
          -q interactive -C gpu --gpus 1 --account=m4293_g \
          pytest pytests/test_basicoperators.py
    
