name: Python Environment Test

on:
  workflow_dispatch:

jobs:
  Python_Environment_Testing:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print checked code and check environments
        run: |
          ls -lah
          echo $(pwd)
          echo $(which python3)
          echo $(which pip3)
      - name: create new virtual environment 
        run: |
          python -m venv .venv 
          source .venv/bin/activate 
          echo $(which python3)
          echo $(which pip3)
